version: "3.8"

services:
  nginx:
    build: nginx
    image: github-readme-stats-nginx:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -sf localhost:80/health-check || exit 1"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 30s
    depends_on:
      - app
    ports:
      - "80:80"

  app:
    build: .
    image: github-readme-stats-app:latest
    #env_file: settings.env
    command: "node express.js"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 64M
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -sf localhost:3000/app-health-check || exit 1"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 30s
