version: "3.8"

services:
  nginx:
    image: ghcr.io/cssnr/docker-nginx-proxy:latest
    environment:
      - SERVICE_PORT=9000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.github-readme-stats-http.rule=Host(`github-readme-stats.cssnr.com`)
        - traefik.http.routers.github-readme-stats-http.entrypoints=http
        - traefik.http.routers.github-readme-stats-http.middlewares=https-redirect
        - traefik.http.routers.github-readme-stats-https.rule=Host(`github-readme-stats.cssnr.com`)
        - traefik.http.routers.github-readme-stats-https.entrypoints=https
        - traefik.http.routers.github-readme-stats-https.tls=true
        - traefik.http.services.github-readme-stats-https.loadbalancer.server.port=80
    depends_on:
      - app
    networks:
      - internal
      - traefik-public

  app:
    image: ghcr.io/smashedr/github-readme-stats:latest
    environment:
      PAT_1: ${PAT_1}
    command: "node express.js"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 64M
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
