version: "3.8"

services:
  nginx:
    build:
      context: nginx
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/smashedr/github-readme-stats-nginx:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    healthcheck:
      test: ["CMD-SHELL", "curl -sf localhost:80/health-check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - app
    networks:
      - internal
      - traefik-public

  app:
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/smashedr/github-readme-stats-app:latest
    command: "node express.js"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 64M
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -sf localhost:3000/app-health-check || exit 1"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 30s
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
