version: "3.8"

services:
  nginx:
    build: nginx
    image: github-readme-stats-nginx:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
    depends_on:
      - app
    ports:
      - "80:80"

  app:
    build: .
    image: github-readme-stats-app:latest
    env_file: settings.env
    command: "node express.js"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 64M
