FROM nginx:mainline

LABEL org.opencontainers.image.source="https://github.com/smashedr/github-readme-stats"
LABEL org.opencontainers.image.description="anuraghazra/github-readme-stats"
LABEL org.opencontainers.image.authors="smashedr"

ENV TZ=UTC

COPY nginx.conf /etc/nginx/nginx.conf
