name: "Build"

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: anuraghazra/github-readme-stats
          path: app

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Bake and Push"
        uses: docker/bake-action@v5
        with:
          files: docker-compose-build.yaml
          push: true

  #deploy:
  #  name: "Deploy"
  #  runs-on: ubuntu-latest
  #  timeout-minutes: 5
  #  needs: [build]
  #
  #  steps:
  #    - name: "Portainer Deploy"
  #      uses: cssnr/portainer-stack-deploy-action@v1
  #      with:
  #        url: https://portainer-o-us-east-1.hosted-domains.com
  #        token: ${{ secrets.PORTAINER_TOKEN }}
  #        file: docker-compose-swarm.yaml
  #        name: github-readme-stats
  #        username: ${{ vars.GHCR_USER }}
  #        password: ${{ secrets.GHCR_PASS }}
  #        env_json: '{"PAT_1": "${{ secrets.GHCR_PASS }}"}'
